def define_properties():
    mushroom_properties = ["gill color",
                           "gill type",
                           "cap shape",
                           "cap color",
                           "cap texture",
                           "hymenium",
                           "stem color",
                           "stem texture",
                           "stem has ring",
                           "stem has volva",
                           "spore print color",
                           "odor",
                           "location",
                           "climate",
                           "season",
                           "host organism",
						   "genus",
						   "species"]

    patient_properties = ["heart rate > 100",
                          "yellow skin or eyes",
						  "blue skin",
                          "upper abdominal pain",
                          "lower abdominal pain",
                          "nausea",
                          "vomiting",
                          "disorientation",
                          "seizures",
                          "myoclonus",
                          "immense thirst",
                          "frequent urination",
                          "dilated pupils",
                          "hallucinations",
                          "headache",
                          "diarrhea",
                          "bloody diarrhea",
                          "vertigo",
                          "burning sensation in limbs",
						  "shortness of breathe",
						  "swelling in lower body",
						  "fatigue",
						  "blood sugar level below 70 mg/dl",
						  "blood pH < 7.35",
						  "loose watery stool",
						  "rectal pain",
						  "trouble swallowing",
						  "loss of vision",
						  "loss of balance",
						  "hypotension",
						  "miosis",
						  "lacrimation",
						  "myalgia",
						  "coma",
						  "in yunnan china",
						  "dizziness",
						  "heart palpitations"]

    return (mushroom_properties, patient_properties)

